
spring.application.name=lms

spring.datasource.url=jdbc:postgresql://localhost:5432/lms_db
spring.datasource.username=postgres
spring.datasource.password=BhNt220#

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true


# Email - replace with your real gmail and app password
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=mazwig739@gmail.com
spring.mail.password=juyd ymbp bqrj efar
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.starttls.required=true

# Microsoft Teams Webhook URL
# Replace this with your actual webhook URL from Teams
teams.webhook.url=https://outlook.office.com/webhook/YOUR_WEBHOOK_URL_HERE
teams.notifications.enabled=true
